[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [Parameter(Mandatory = $false)]
    [string]$Namespace = "Tenko.Native.Generated"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $InputPath)) {
    throw "Input file not found: $InputPath"
}

$rawJson = [IO.File]::ReadAllText($InputPath, [Text.Encoding]::UTF8).Trim()
if ([string]::IsNullOrWhiteSpace($rawJson)) {
    throw "Locations json is empty: $InputPath"
}

$locations = $rawJson | ConvertFrom-Json
if (-not ($locations -is [System.Collections.IEnumerable])) {
    $locations = @($locations)
}

$items = @()
foreach ($loc in $locations) {
    if ($null -ne $loc -and -not [string]::IsNullOrWhiteSpace($loc.ToString())) {
        $escaped = $loc.ToString().Replace('\', '\\').Replace('"', '\"')
        $items += "            `"$escaped`""
    }
}

if ($items.Count -eq 0) {
    throw "No valid locations found in: $InputPath"
}

$itemsBlock = $items -join ",`r`n"
Write-Output "[Generate-EmbeddedLocations] Loaded locations from '$InputPath' ($($items.Count) locations)."

$content = @"
// <auto-generated />
using System;
using System.Collections.Generic;

namespace $Namespace
{
    public static class EmbeddedLocations
    {
        private static readonly string[] _locations = new string[]
        {
$itemsBlock
        };

        public static IReadOnlyList<string> GetLocations() => _locations;
    }
}
"@

$outputDir = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDir) -and -not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

[IO.File]::WriteAllText($OutputPath, $content, [Text.Encoding]::UTF8)
Write-Output "[Generate-EmbeddedLocations] Generated embedded source: '$OutputPath'."
