[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath,

    [Parameter(Mandatory = $false)]
    [string]$Namespace = "Tenko.Native.Generated"
)

$ErrorActionPreference = "Stop"

$serverUrl = ""
$apiKey = ""
$clientId = ""
$enabled = $false

if (Test-Path -LiteralPath $InputPath) {
    try {
        $rawJson = [IO.File]::ReadAllText($InputPath, [Text.Encoding]::UTF8).Trim()
        if (-not [string]::IsNullOrWhiteSpace($rawJson)) {
            $config = $rawJson | ConvertFrom-Json
            if ($null -ne $config) {
                if ($null -ne $config.PSObject.Properties['serverUrl']) { $serverUrl = [string]$config.serverUrl }
                if ($null -ne $config.PSObject.Properties['apiKey']) { $apiKey = [string]$config.apiKey }
                if ($null -ne $config.PSObject.Properties['clientId']) { $clientId = [string]$config.clientId }
                if ($null -ne $config.PSObject.Properties['enabled']) { $enabled = [bool]$config.enabled }
            }
        }
    }
    catch {
        Write-Warning "[Generate-EmbeddedServerConfig] Failed to parse $($InputPath): $_. Defaulting to disabled."
    }
}
else {
    Write-Output "[Generate-EmbeddedServerConfig] $($InputPath) not found. Defaulting to disabled."
}

$escapedUrl = if ($serverUrl) { $serverUrl.Replace('\', '\\').Replace('"', '\"') } else { "" }
$escapedApiKey = if ($apiKey) { $apiKey.Replace('\', '\\').Replace('"', '\"') } else { "" }
$escapedClientId = if ($clientId) { $clientId.Replace('\', '\\').Replace('"', '\"') } else { "" }
$enabledLiteral = if ($enabled -and -not [string]::IsNullOrWhiteSpace($serverUrl)) { "true" } else { "false" }

Write-Output "[Generate-EmbeddedServerConfig] Loaded server config: ServerUrl='$serverUrl', Enabled=$enabledLiteral."

$content = @"
// <auto-generated />
using System;

namespace $Namespace
{
    public static class EmbeddedServerConfig
    {
        public static string ServerUrl => "$escapedUrl";
        public static string ApiKey => "$escapedApiKey";
        public static string ClientId => "$escapedClientId";
        public static bool IsEnabled => $enabledLiteral;
    }
}
"@

$outputDir = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDir) -and -not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

[IO.File]::WriteAllText($OutputPath, $content, [Text.Encoding]::UTF8)
Write-Output "[Generate-EmbeddedServerConfig] Generated embedded source: '$OutputPath'."
