[CmdletBinding()]
param(
    [Parameter(Mandatory = $true)]
    [string]$InputPath,

    [Parameter(Mandatory = $true)]
    [string]$OutputPath
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path -LiteralPath $InputPath)) {
    throw "Input file not found: $InputPath"
}

$passphrase = [IO.File]::ReadAllText($InputPath, [Text.Encoding]::UTF8).TrimEnd([char[]]"`r`n")
if ([string]::IsNullOrWhiteSpace($passphrase)) {
    throw "Passphrase is empty: $InputPath"
}
Write-Output "[Generate-EmbeddedPassphrase] Loaded students.passphrase from '$InputPath' ($($passphrase.Length) chars)."

$plainBytes = [Text.Encoding]::UTF8.GetBytes($passphrase)
$maskBytes = New-Object byte[] $plainBytes.Length
$rng = [Security.Cryptography.RandomNumberGenerator]::Create()
try {
    $rng.GetBytes($maskBytes)
}
finally {
    $rng.Dispose()
}

$obfuscatedBytes = New-Object byte[] $plainBytes.Length
for ($i = 0; $i -lt $plainBytes.Length; $i++) {
    $obfuscatedBytes[$i] = $plainBytes[$i] -bxor $maskBytes[$i]
}

$maskBase64 = [Convert]::ToBase64String($maskBytes)
$dataBase64 = [Convert]::ToBase64String($obfuscatedBytes)

$content = @"
// <auto-generated />
using System;
using System.Text;

namespace Tenko.Native.Generated
{
    public static class EmbeddedStudentsPassphrase
    {
        private const string MaskBase64 = "$maskBase64";
        private const string DataBase64 = "$dataBase64";

        public static string GetPassphrase()
        {
            byte[] mask = Convert.FromBase64String(MaskBase64);
            byte[] data = Convert.FromBase64String(DataBase64);
            if (mask.Length != data.Length)
            {
                return string.Empty;
            }

            for (int i = 0; i < data.Length; i++)
            {
                data[i] = (byte)(data[i] ^ mask[i]);
            }

            return Encoding.UTF8.GetString(data);
        }
    }
}
"@

$outputDir = Split-Path -Parent $OutputPath
if (-not [string]::IsNullOrWhiteSpace($outputDir) -and -not (Test-Path -LiteralPath $outputDir)) {
    New-Item -ItemType Directory -Path $outputDir | Out-Null
}

[IO.File]::WriteAllText($OutputPath, $content, [Text.Encoding]::UTF8)
Write-Output "[Generate-EmbeddedPassphrase] Generated embedded source: '$OutputPath'."
